#!/bin/bash
# Strip Cursor / AI "made by" trailers from a git commit message file.
# Human Co-authored-by lines stay (GitHub Contributors).
# Organization: Black Rain Labs — Research & Development Division
set -euo pipefail

file="${1:?commit message file}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

awk '
function skip() {
  t = tolower($0)
  if (t ~ /^[[:space:]]*co-authored-by:[[:space:]].*cursor/) return 1
  if (t ~ /^[[:space:]]*co-authored-by:[[:space:]].*cursoragent@/) return 1
  if (t ~ /^[[:space:]]*(made-with|made by|created by|generated by|signed-off-by:)[[:space:]].*cursor/) return 1
  return 0
}
{
  if (skip()) next
  lines[++n] = $0
}
END {
  while (n > 0 && lines[n] ~ /^[[:space:]]*$/) n--
  for (i = 1; i <= n; i++) print lines[i]
}
' "$file" > "$tmp"
cat "$tmp" > "$file"
